### ISSUE TITLE
AD0001 Analyzer 'AspNetCoreAnalyzers.AttributeAnalyzer' threw an exception of type 'System.IndexOutOfRangeException'

### ISSUE THREAD

**Issue by Ekkeir** [DotNetAnalyzers/AspNetCoreAnalyzers#70]
### The problem
The warning below is emitted when building my project where route is defined on class.
`CSC : warning AD0001: Analyzer 'AspNetCoreAnalyzers.AttributeAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.`

### To Reproduce
Create new empty ASP Net Core Web Application
Add the following class
```c#
using Microsoft.AspNetCore.Mvc;

namespace AnalyzerBugRepro
{
    [ApiController]
    [Route("api/")]
    public class GrantStubController : ControllerBase
    {
    }
}

```

Build the project
Observe the error in build output.

**Comment by JohanLarsson** [comment]
Thanks for reporting, this is a perfect issue!
Never worry about creating issues, no issue is worse than duplicate issue or poor issue.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/AspNetCoreAnalyzers/0.2.0.1-dev

Sorry about the bug and the slow fix.

**Comment by Ekkeir** [comment]
As long as it's fixed, thanks a lot!

**Comment by sungam3r** [comment]
I think `0.2.0.1-dev` is not [semver](https://semver.org/) compatible version, `0.2.0-dev1` would be better.

**Comment by JohanLarsson** [comment]
> I think 0.2.0.1-dev is not semver compatible version, 0.2.0-dev1 would be better.

@sungam3r does it break nuget.exe so the package should be republished with correct version?

**Comment by sungam3r** [comment]
I have installed the package from VS 2019. Maybe some other clients might have problems, I don't know.
