### ISSUE TITLE
AD0001 Could not load file or assembly 'Gu'Roslyn.Extensions' since Visual Studio 2022 install

### ISSUE THREAD

**Issue by richardb355** [DotNetAnalyzers/AspNetCoreAnalyzers#71]
Since installing Visual Studio 2022, we experience build warnings using this package. We get warnings in both VS 2022 and VS 2019. The error we get is:

`AD0001	Analyzer 'AspNetCoreAnalyzers.AttributeAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Gu.Roslyn.Extensions, Version=0.4.4.1, Culture=neutral, PublicKeyToken=4b04740f2fd5868f' or one of its dependencies. The system cannot find the file specified.'.`

I'm guessing this may be linked to [this issue](https://github.com/GuOrg/Gu.Analyzers/issues/315)?

**Comment by JohanLarsson** [comment]
I'm always surprised this package has users, wrote it while bored blocked waiting for another thing.
Sorry about the bug, hopefully the new version works better: https://www.nuget.org/packages/AspNetCoreAnalyzers/0.3.0

**Comment by JohanLarsson** [comment]
I never write any web so don't use this analyzer hence we rely on issues for things not working.
